version: '3.8'

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    container_name: integration-tests-mysql
    ports:
      - '6666:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
    healthcheck:
      test: mysql --user=root --password=123 --execute='show databases'
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
      start_interval: 5s
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/init.sql
