version: '3.1'

services:

  db:
    image: mysql
    restart: always
    container_name: integration-tests-mysql
    ports:
      - "6666:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
